# Generated by Django 4.0.4 on 2022-05-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('CityName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('WarehouseID', models.AutoField(primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=100)),
            ],
        ),
    ]
