# Generated by Django 4.0.4 on 2022-05-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='CityName',
            new_name='City',
        ),
    ]
